language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install flake8"
# command to run tests
script: python manage.py test
addons:
  postgresql: "9.3"
before_script:
  - flake8 whats_fresh/
  - psql -c 'create database whats_fresh;' -U postgres
  - psql -U postgres -c "create extension postgis;" whats_fresh

