language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python manage.py test
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test_whats_fresh;' -U postgres
  - psql -U postgres -c "create extension postgis"

